### ISSUE TITLE
Doesn't fully install

### ISSUE THREAD

**Issue by BGundlach** [concrete5/composer#12]
After running the installation through composer and accessing the site through my browser, the installation page popped up.  I realized it hadn't generated the database.php in the application/config/ directory. Ought to be an easy fix.

**Comment by mlocati** [comment]
Composer "just" fetches concrete5.
In order to install concrete5 via a terminal interface you can run the CLI command `concrete/bin/concrete5 c5:install`

You can specify all the arguments (database name, passwords, ...), or you can use the `-i` option for an interactive CLI setup

**Comment by BGundlach** [comment]
I ran it interactively. It said it was finished installing and after
manually adding the database.php I could see everything that had been
installed.

**Comment by mlocati** [comment]
I'm sorry but I don't understand what you mean with "*after manually adding the database.php*" (adding what? where?).

And with "*I could see everything that had been installed*" are you confirming that everything is ok for you?

**Comment by KorvinSzanto** [comment]
This isn't really making sense to me. The concrete5 install routine is managed by concrete5 itself and should install a `database.php` file to `/application/config`
