### ISSUE TITLE
Files missing when installing Concrete5 via composer

### ISSUE THREAD

**Issue by adamlindqvist** [concrete5/composer#13]
Since today(?) it is not possible to install a new concrete5 project with composer. 
I'm typing composer `$ create-project concrete5/composer new_project` which gives the following output:

```bash
Installing concrete5/composer (v1.0.0)
  - Installing concrete5/composer (v1.0.0): Loading from cache
Created project in new_project
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.4.0): Loading from cache
  - Installing wikimedia/composer-merge-plugin (v1.4.1): Loading from cache
  - Installing concrete5/core (8.2.1): Loading from cache
Writing lock file
Generating autoload files
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```
However it seems to not install properly since the `public/concrete` folder is missing after the install.

This did work last friday (17 nov) but not today. Has anything happend since then?

**Comment by a3020** [comment]
@adamlindqvist I just tested this and it works for me.

**Comment by mlocati** [comment]
@KorvinSzanto wrote on Slack that this was just a temporary problem if the concrete5 composer repository

**Comment by adamlindqvist** [comment]
@a3020 & @mlocati Yeah it seems to work now again.

@KorvinSzanto Any idea of what went wrong?

**Comment by KorvinSzanto** [comment]
This was an issue with the [core splitter](https://github.com/concrete5/core_splitter) taking too long to complete and failing to completely split the repository. To resolve the issue I updated the configuration of the core_splitter to only run on push and also moved it to run on a more powerful machine.
