### ISSUE TITLE
Add instructions to use the latest development version

### ISSUE THREAD

**Issue by a3020** [concrete5/composer#14]
Maybe we can add to the readme that if you want to use the latest development version you can replace 

https://github.com/concrete5/composer/blob/d019cb550d45f27664e4aa8c78fdf4fecf0f69db/composer.json#L9

with

```
"concrete5/core": "8.x-dev"
```

**Comment by KorvinSzanto** [comment]
Yeah, a pull request would be great. We also have the 8.x-dev option of this project:
`composer create-project concrete5/composer:8.x-dev path/`

**Comment by KorvinSzanto** [comment]
https://github.com/concrete5/composer/commit/6900046ce6f53cbdd5daa6cf5ab01cc8386c8395
