### ISSUE TITLE
Consider removing 'stub' folders in /application

### ISSUE THREAD

**Issue by a3020** [concrete5/composer#15]
The `application` folder contains a lot of (empty) folders that are not really necessary. Why not remove them by default?

https://github.com/concrete5/composer/tree/master/public/application

**Comment by KorvinSzanto** [comment]
Because that'd make it hard to know the name of the directory you need later if you need to use one of these empty directories. IMO we should leave them.

**Comment by aembler** [comment]
👍to what Korvin said. That’s always been the rationale for having the empty directories.
