### ISSUE TITLE
When should we update required version of concrete5/core?

### ISSUE THREAD

**Issue by hissy** [concrete5/composer#16]
Now the composer.json in this repository requires 8.2.x, but 8.3.0 is already released 20 days ago.

```
"concrete5/core": "^8.2"
```

Should we update the version to `^8.3`? Or, just change to `8.*` ?

**Comment by aembler** [comment]
👍

**Comment by KorvinSzanto** [comment]
I don't really see a reason for this, the reason why we require greater than 8.2 is because we do not support 8.1, not because we intend for that version to be installed.

**Comment by KorvinSzanto** [comment]
Just for proof that this isn't causing issues: https://semver.mwl.be/#?package=concrete5%2Fcore&version=%5E8.2&minimum-stability=stable

**Comment by hissy** [comment]
Oh, I understand. thank you. https://getcomposer.org/doc/articles/versions.md#tilde-version-range-

**Comment by KorvinSzanto** [comment]
That all said we will definitely need to adjust the project when v9 is closer to release.
