### ISSUE TITLE
Error: Failed to create cache path

### ISSUE THREAD

**Issue by milinmestry** [concrete5/composer#20]
Using the composer installation on the terminal the process finish with success, but when I see the site I got error: 

### An unexpected error occurred.
**Failed to create cache path.**

![concrete5-installation-complete](https://user-images.githubusercontent.com/6246118/42410650-a29726ce-820a-11e8-8643-0b6fe2b7c8cb.png)
![concrete5-cms-error-cache-path](https://user-images.githubusercontent.com/6246118/42410653-b9b6a398-820a-11e8-9d05-42bbfaa12a8b.png)

**Comment by olsgreen** [comment]
Sounds like a permissions problem. Make sure your application/files
directory is writable by the web server.

**Comment by aembler** [comment]
I agree with @olsgreen – I see this most office when I run via the command line and then the user that owns the files/ isn't the same as the web user, so the web user then can't create files/cache when visiting the website.

I'm going to close this, but I will agree that this is irritating – this shouldn't matter; the files/ directory should be world writable so I'm not sure why the the web user can't create the files/cache directory in this instance.
