### ISSUE TITLE
8.x branch contains errors

### ISSUE THREAD

**Issue by a3020** [concrete5/composer#23]
When running 

> composer create-project -n concrete5/composer:8.x-dev the_oregon_trail

You end up with a non-working installation. That is, I think, because of this .js override: 
https://github.com/concrete5/composer/blob/8.x/public/application/js/app.js

![afbeelding](https://user-images.githubusercontent.com/1431100/47552222-7f155080-d904-11e8-9a36-7aaa2e5e8a14.png)

**Comment by a3020** [comment]
This override also causes issues: https://github.com/concrete5/composer/blob/master/public/application/css/main.css

**Comment by a3020** [comment]
Once installed, the issue can be resolved by removing both files and then clearing the cache.

**Comment by KorvinSzanto** [comment]
Forgot to manage this issue, we've resolved this by removing the 8.x branch entirely.
