### ISSUE TITLE
Security alerts

### ISSUE THREAD

**Issue by ghost** [concrete5/composer#24]
I'm receiving security alerts from Github. Anyone else?

>We found potential security vulnerabilities in your dependencies.
Only the owner of this repository can see this message. 

![image](https://user-images.githubusercontent.com/1699931/51909985-0ddab300-23b5-11e9-8b09-239a05fad469.png)

The first two are not related to C5, but the others are.

**Comment by KorvinSzanto** [comment]
In both of these cases, you can likely just update your npm dependencies and commit the new package-lock.json files.
