### ISSUE TITLE
PDOStatement::free() error on install

### ISSUE THREAD

**Issue by HubbleCommand** [concrete5/composer#34]
Hello.

I'm trying to install Concrete5 with composer, and have done it quite a few times before. However when I tried my usual method today, I got the following error:

```
PHP Fatal error:  Declaration of Concrete\Core\Database\Driver\PDOStatement::free() must be compatible with Doctrine\DBAL\Driver\PDOStatement::free(): void in /var/www/html/think_data/public/concrete/src/Database/Driver/PDOStatement.php on line 34
Whoops\Exception\ErrorException: Declaration of Concrete\Core\Database\Driver\PDOStatement::free() must be compatible with Doctrine\DBAL\Driver\PDOStatement::free(): void in file /var/www/html/think_data/public/concrete/src/Database/Driver/PDOStatement.php on line 34
Stack trace:
  1. Whoops\Exception\ErrorException->() /var/www/html/think_data/public/concrete/src/Database/Driver/PDOStatement.php:34
   | array(1) {
   |   [0]=>
   |   string(137) "Declaration of Concrete\Core\Database\Driver\PDOStatement::free() must be compatible with Doctrine\DBAL\Driver\PDOStatement::free(): void"
   | }

  2. Whoops\Run->handleError() /var/www/html/think_data/vendor/filp/whoops/src/Whoops/Run.php:408
   | array(0) {
   | }

  3. Whoops\Run->handleShutdown() [internal]:0
   | array(0) {
   | }

```

Any ideas?

**Comment by KorvinSzanto** [comment]
It sounds like you might've installed composer dependencies with a different PHP version to the one you're using to install concrete5, try using the same php version for both

**Comment by mlocati** [comment]
Could you check whch version of doctrine/dbal is installed? You should find it in the composer.lock file, right under a line like this:
`"name": "doctrine/dbal",`

**Comment by mlocati** [comment]
My first guess is that concrete5 is not compatible with doctrine/dbal version 2.11.0, we should stay at max at 2.10.x.
See https://github.com/doctrine/dbal/blob/2.11.0/lib/Doctrine/DBAL/Driver/PDOStatement.php#L262 vs https://github.com/concrete5/concrete5/blob/8.5.4/concrete/src/Database/Driver/PDOStatement.php#L34 (the method has a different signature)

**Comment by HubbleCommand** [comment]
Thanks @mlocati , it was an issue with the dbal version. I just changed the version in composer and it installs fine.

**Comment by mlocati** [comment]
@HubbleCommand it's a real issue we should address in next concrete5 versions - let's continue the discussion at https://github.com/concrete5/concrete5/issues/9050
