### ISSUE TITLE
Ambiguous class resolution, "Normalizer"

### ISSUE THREAD

**Issue by Jeemusu** [concrete5/composer#35]
I am attempting to install concrete5 via composer, the environment is 7.4. I have another concrete5 site of the same version working in the same environment with no problems (however it was installed by extracting the zip from the website).

When executing the following command:

`composer create-project -n concrete5/composer project`

I receive the following warning during the install process:

`Warning: Ambiguous class resolution, "Normalizer" was found 2x: in "/var/www/project/vendor/patchwork/utf8/src/Normalizer.php" and "/var/www/project/vendor/voku/portable-utf8/src/Normalizer.php", the first will be used.`

Upon attempting to finalize the install via the command line interface or via the browser I receive the following error:

`PHP Fatal error:  Cannot redeclare normalizer_is_normalized() (previously declared in /var/www/project/vendor/symfony/polyfill-intl-normalizer/bootstrap.php:15) in /var/www/project/vendor/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php on line 20`

Seems to be some kind of clash with the `symfony/polyfill-intl-normalizer` and `patchwork/utf8` dependencies.

**Comment by Jeemusu** [comment]
Sorry, I closed this thinking it was related to the cli being php 7.4. However upon changing both Apache and the cli to 7.3 I receive the same warnings/errors.

**Comment by mlocati** [comment]
Could you try to enable the `intl` php extension? It should fix the issue.

**Comment by Jeemusu** [comment]
That appears to have fixed the issue. Thank you!

**Comment by ahukkanen** [comment]
I got this same issue. Is the `intl` extension a hard requirement for concrete5?

I don't see it listed here:
https://documentation.concrete5.org/developers/introduction/system-requirements

There should be also upgrade notes pointing out that this extension should be enabled (in case it is necessary).
