### ISSUE TITLE
Requiring the dev-8.6.x-dev version of concrete5/core seems to break the dependency installation

### ISSUE THREAD

**Issue by puka-tchou** [concrete5/composer#36]
I'm trying to upgrade `concrete5/core` to `dev-8.6.x-dev` to take advantage of the multisite options. When requiring the new version of `concrete5/core`, everything seems to work nice, however, this error pops up when going to the website:

```
Third party libraries not installed. Make sure that composer has required libraries in the concrete/ directory.
```

It seems that Composer is no longer installing the dependencies of `public/concrete/composer.json`. I can mitigate the issue by manually installing the dependencies like shown below, but this is a strange behavior and is likely to cause other issues down the road:

```
cd public/concrete
composer i
```

Here is my full root `composer.json` file:

```json
{
  "name": "concrete5/composer",
  "description": "A fully featured skeleton for a composer managed concrete5 site",
  "type": "project",
  "license": "MIT",
  "prefer-stable": true,
  "autoload": {
    "psr-4": {
      "ConcreteComposer\\" : "./src"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "ConcreteComposer\\" : "./tests"
    }
  },
  "require": {
    "composer/installers": "^1.3",
    "concrete5/core": "dev-8.6.x-dev#c4c8410",
    "concrete5/dependency-patches": "^1.4.0",
    "doctrine/dbal": "2.10"
  },
  "require-dev": {
    "phpunit/phpunit": "~4.3|^8.0",
    "mockery/mockery": "^0.9.9|^1.2",
    "squizlabs/php_codesniffer": "^3.5",
    "phpmd/phpmd" : "@stable",
    "phpstan/phpstan": "^0.12.33"
  },
  "config": {
    "preferred-install": "dist"
  },
  "extra": {
    "allow-subpatches": [
      "concrete5/dependency-patches"
    ],
    "branch-alias": {
      "dev-8.x": "8.x-dev"
    },
    "installer-paths": {
      "public/concrete": ["type:concrete5-core"],
      "public/application/themes/{$name}": ["type:concrete5-theme"],
      "public/packages/{$name}": ["type:concrete5-package"],
      "public/application/blocks/{$name}": ["type:concrete5-block"]
    }
  },
  "scripts": {
    "test": "phpunit",
    "phpmd-analyse-code": "vendor/bin/phpmd public/application/ html cleancode,codesize,controversial,design,naming,unusedcode --exclude */public/application/config/* > rapports/phpmd.html",
    "phpstan-analyse-code": "vendor/bin/phpstan clear-result-cache && vendor/bin/phpstan analyse --configuration phpstan.neon --error-format=prettyJson > rapports/phpstan.json",
    "analyse-code": "composer run-script phpmd-analyse-code&&composer run-script phpstan-analyse-code",
    "phpcs": "phpcs --standard=PSR1,PSR12 --exclude=PSR1.Files.SideEffects --extensions=php --ignore=config/*,files/* --report-junit=test-reports/phpcs.xml --report-full public/application",
    "phpcbf":"phpcbf --standard=PSR1,PSR12 --extensions=php --ignore=config/*,files/* --report-summary"
  }
}
```

**Comment by puka-tchou** [comment]
Sorry for the unnecessary noise, it was actually a problem coming from `public/application/bootstrap/autoload.php`.

**Comment by martbase** [comment]
Hey @puka-tchou Are you using a custom autoloader for concretecms with phpstan?

I've been trying to get phpstan (installed globally) to work with my local installation of concretecms ver 9.4.6 on a Windows box without success (PHP, Apache and MySQL 8 installed/configured manually). 
Concrete CMS was installed through the browser after extracting the latest release zip file into a sub-directory on the web root.

The setup works fine for laravel projects where phpstan is able to analyze code and report issues but I haven't managed to get it to work with concretecms whether concrete/dispatcher.php or a custom autoloader is referenced in bootstrapFiles.

This issue https://github.com/phpstan/phpstan/issues/2257 mentions using a custom autoloader as a solution.
Are there any packages similar to [larastan ](https://github.com/larastan/larastan) or custom stubs publicly available that can be used to make it easier for concretecms to work with phpstan?

@jlucki it would be awesome if you could share your custom autoloader solution or provide some guidance on how to go about this.

PS: I wasn't sure whether to open a new issue for this hence why I commented here as phpstan is specified in composer.json in this issue.
