### ISSUE TITLE
Version 9 support

### ISSUE THREAD

**Issue by KorvinSzanto** [concrete5/composer#39]
Version 9 has a few issues that prevent us from upgrading by default at the moment due to PHP 8 incompatibility

- `theorchard/monolog-cascade`: No PHP 8 support, blocks install
- `theorchard/monolog-cascade`: Dev dependency, requires `minimum-stability: dev`
- `laminas/cache`: Laminas includes a ton of cache adapters that are abandoned and don't support PHP 8, [they have a recommended fix](https://docs.laminas.dev/laminas-cache/installation/#avoid-unused-cache-adapters-are-being-installed). Not sure yet if that should go in the core or in this repo.

**Comment by KorvinSzanto** [comment]
If you're not running PHP 8 and you'd like to update to version 9 you can do so by editing the composer.json with the following steps:

1. **Remove `doctrine/dbal` and `concrete5/phpass-compat` dependencies**, they aren't needed any more
2. **Remove `hautelook/phpass` from `provide`**, this isn't something the core expects anymore
3. **Set `minimum_stability` to `dev`**, `monolog-cascade` is a dev dependency so we have to set our minimum stability.
4. **Change the `concrete5/core` requirement to `9.0.0`**

**Comment by aembler** [comment]
Since it sounds like monolog cascade has been abandoned we should probably just fork it, remove dev as the minimum stability, and mark it as compatible with php 8 (assuming it is of course)

Regarding laminas - yeah we shouldn't need any of those backends. We should just follow their advice about blackholing them in the core, I would think

**Comment by katzueno** [comment]
Hey I was testing composer install.
I think 9.0.1 is released and this problem is solved so that it's ready to update composer?

**Comment by KorvinSzanto** [comment]
Agreed, we can update this repo. I'm on vacation for a couple of weeks so a PR would be much appreciated.
