### ISSUE TITLE
Movement from Ubuntu to MacOS, can't get v9 going again

### ISSUE THREAD

**Issue by davedew** [concrete5/composer#41]
Hello, I started a V9 composer project a week ago on my local Ubuntu box.  I recently received a new Mac M1 and found it to be faster than my Ubuntu box so I switched.  I setup the same version of PHP, MySQL, etc on the Mac via Homebrew and cloned my git repo and did my composer installation.  I pulled over the application/config directory, application/files directory and the dump of the database. I tweaked the config for the new database connection and then turned all cache settings off.  Cleared the cache and linked the site up to run.  Unfortunately, I'm running in to an issue.  Here is the error that presents: 

Warning: require(/Users/david/Repositories/BOMA-2021/vendor/composer/../../src/helpers.php): failed to open stream: No such file or directory in /Users/david/Repositories/BOMA-2021/vendor/composer/autoload_real.php on line 78

Fatal error: require(): Failed opening required '/Users/david/Repositories/BOMA-2021/vendor/composer/../../src/helpers.php' (include_path='/Users/david/Repositories/BOMA-2021/public/concrete/vendor:.:/opt/homebrew/Cellar/php@7.4/7.4.27/share/php@7.4/pear') in /Users/david/Repositories/BOMA-2021/vendor/composer/autoload_real.php on line 78

I have been able to move Concrete 5.8.7 projects over without this issue, but the v9 one I cannot seem to get working.  I can also install new V9 projects and those work fine.  Any insight would be great!

Thanks!

**Comment by hissy** [comment]
Please post it on [forum](https://forums.concretecms.org/c/installation/5) if you want to get support from the community.

**Comment by davedew** [comment]
OK done.  Thanks!
