### ISSUE TITLE
An example in README doesn't works

### ISSUE THREAD

**Issue by hissy** [concrete5/composer#44]
```
$ composer create-project -n concretecms/composer the_oregon_trail
```

I think you forgot to change `concrete5/core` to `concretecms/composer` on packagist

https://packagist.org/packages/concrete5/core

**Comment by KorvinSzanto** [comment]
This works today so it has been resolved: https://packagist.org/packages/concretecms/composer

For the record, `concretecms/composer` is this project while `concretecms/core` (`concrete5/core`) is https://github.com/concretecms/concretecms-core
