### ISSUE TITLE
Hot reload not applying scss changes

### ISSUE THREAD

**Issue by RLHawk1** [concrete5/composer#48]
In my page_theme, I have
```php
public function registerAssets() {
    $this->requireAsset(mixAsset('/packages/mypackage/themes/mytheme/css/global.css'));
    $this->requireAsset(mixAsset('/packages/mypackage/themes/mytheme/js/global.min.js'));
}
```
And I'm running `npm run hot`.

When I change the javascript file, the hot swapping works. But when I change the scss file, the hot swapping doesn't work. If I change the scss file, then change the javascript file, it does swap in the CSS updates, but not if I only edit the scss file.

**Comment by KorvinSzanto** [comment]
You might see some improvement using laravel mix 6 but if not this is [a known issue](https://github.com/laravel-mix/laravel-mix/issues/92). One way to work around this is to import your SCSS into your js file rather than building them separately.
