### ISSUE TITLE
Composer Install: Missing PHP packages

### ISSUE THREAD

**Issue by MBfromOK** [concrete5/composer#52]
While installing Concrete with Composer the process repeatedly failed with errors like the following:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - concrete5/core[9.2.0, ..., 9.2.8] require ext-zip * -> it is missing from your system. Install or enable PHP's zip extension.
    - Root composer.json requires concrete5/core ^9.2 -> satisfiable by concrete5/core[9.2.0, ..., 9.2.8].
```
In my case there were ~8 php modules that needed to be installed to meet requirements. This meant that I had to locate the php8.1-* module 1 at a time, use apt-get to download and install them, then clear the destination folder and re-run the composer command only to discover that there was another missing php module.

Proposal: 

1. Do a check for all required php packages/components and then a display a list of missing packages
2. Add support for resuming a composer install with a partially populated folder

**Comment by mlocati** [comment]
Concrete isn't involved at all in the `composer install` stage: everything is performed by composer. You should report composer issues to the composer project.

BTW:

> then clear the destination folder

You don't need to perform that step.

Also: hve you tried running `composer check-platform-reqs` ?

**Comment by MBfromOK** [comment]
> Concrete isn't involved at all in the `composer install` stage: everything is performed by composer. You should report composer issues to the composer project.
> 
> BTW:
> 
> > then clear the destination folder
> 
> You don't need to perform that step.
> 
> Also: hve you tried running `composer check-platform-reqs` ?

I have had no contact with Concrete CMS in 5-10 years and just remembered liking the clean layout. So I went to the page to see if it still existed and then looked at how I would go about loading it to a webserver.  The directions on the page said the best method was to use composer and gave a one line command.

Running the one line command produced less than a working website and returned errors that made it a hassle to get anything working.

> > then clear the destination folder
> 
> You don't need to perform that step.

I stated this step because when I tried to re-run the one liner Composer command after fixing the first missing package I was given an error message that the destination was not empty.

> Also: hve you tried running `composer check-platform-reqs` ?

No, I had never heard of composer before this install and used apt-get install Composer to enable the command; Neither the download page (Concrete website) or the Install process listed any required packages or stated that there was a command to run to validate the required packages were in place before installing with Composer.

**Comment by MBfromOK** [comment]
Thanks for your reply, if there is no desire or plan to add any clarification to the download & install directions on the Concrete download page then I guess this should just be closed.

**Comment by mlocati** [comment]
If you are not familiar with the Composer command and command line tools in general, you should install Concrete by downloading it from https://www.concretecms.org/download (I don't think teaching how to use Composer should be delegated to the Concrete community)

**Comment by KorvinSzanto** [comment]
If you must install concrete in an environment that doesn't have the required extensions, you can do so by using `composer install --ignore-platform-reqs`.
