### ISSUE TITLE
Add a branch to install the develop branch of the core?

### ISSUE THREAD

**Issue by mlocati** [concrete5/composer#8]
What about adding a branch here to let users install the latest development version of concrete5?

The composer.json in that branch should contain something like

```json
{
    "require": {
        "composer/installers": "^1.3",
        "concrete5/core": "dev-develop"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

That way, we'd get https://github.com/concrete5/concrete5-core/tree/develop

**Comment by KorvinSzanto** [comment]
So now:

`composer create-project concrete5/composer` gets you 8.2.1 (or whatever is latest stable)   
`composer create-project concrete5/composer:8.x-dev` gets you the current develop upstream
