### ISSUE TITLE
Version 8.2.0 vs 8.2

### ISSUE THREAD

**Issue by mlocati** [concrete5/composer#9]
The currently tagged version `8.2.0` [resolves to `^8.2`](https://github.com/concrete5/composer/blob/v8.2.0/composer.json#L9), that is, you may get greater versions (for instance 8.2.9). This can be misleading.

I'd create the following tags:
- tag `8` => `"concrete5/core": "^8"` in composer (so that we install any 8.x version)
- tag `8.2` => `"concrete5/core": "^8.2"` in composer (so that we install any 8.2 version)
- ... and so on

If you really have time, we could also add more specific tags (`8.2.0`, `8.2.1`, ...), but that's not so necessary IMHO

**Comment by KorvinSzanto** [comment]
The tags have been updated, they should track versions of concrete5/composer independent of the core.
